ECMWF API Adapter and Weather Provider
orion-junkins/river-level-forecasting pull request #184
Opened 2024-02-13 22:28 UTC by dunnlu

Added ecmwf_adapter, which calls the open meteo API through the ECMWF model, (with Open Meteo's python code for requests). 

Added weather_provider_ecmwf, which calls get_current and get_historical from ecmwf_adapter, parses through the data, creates a weather datum object, and adds the data to the weather datum, returning a list of weather datums correlating with the requested list of locations. 

Added demo_weather_provider_ecmwf, which demos the basic functionalities of the new weather provider.

Added test_ecmwf_adapter, which tests the basic functionalities of the ecmwf_adapter, in this case testing whether the requested location and returned location are the same..

Added test_weather_provider_ecmwf, which tests the instantiation and data storage of the weather provider. For now, it calls for actual data, but in the near future, I will create a fake WeatherApiResponse and api adapter so that the testing does not actually call for any data, but instead just tests the functionality of the weather provider itself. 

Adjusted the conda environment and environment_gpu to include the new dependencies, for compatibility with the new Open Meteo python API call.

2024-02-14 09:13 UTC, orion-junkins commented
For failing tests, a lot of them were caused by some left over work in progress Code in the old api weather provider. I went ahead and reverted that and comitted which fixed a lot of them. https://github.com/orion-junkins/river-level-forecasting/pull/184/commits/f49330aad56524f18d935195549cf431f858c983

Shouldn't have affected your adapter but we can revert if we need to. 

Looks like there are still two failures related to ECMWF code that are identical to what I was getting trying to run the demo script. These are the main thing you need to fix. Is demo script working on your end? 

Also I get an error regarding incorrect datetime indexing but this also appears in main - I'll see if I can fix this one tonight.

Also looks like a bunch of small flake 8 issues - VScode has python formatting built in which makes it faster to fix (I think shift + Ctrl + P and search "format" should get you there).

Also some mypy issues, let me know if mypy passes local but git still has issues, sometime some weirdness in remote environment with mypy.

Overall code looks nice!! Just some things to iron out and we can merge 👍

2024-02-15 22:26 UTC, dunnlu commented
All tests now pass. The only caveat is that mypy skips a lot of the checks on the new packages installed (included in environment.yml at the bottom), since they do not have associated library stubs.

2024-02-16 13:57 UTC, orion-junkins requested changes
Really nice work! I made a couple of small tweaks myself (see recent commits, main change was figuring out how to get a non empty units dict) and highlighted a couple for you to work on. 

1. Prune the shared param list (looks like some variables don't have complete recent data so exclude those for now)
2. Update the demo script to only use valid variables after that pruning.
3. Remove extraneous comments in one or two places I highlighted

Feel free to make a single commit with something like "small tweaks following PR review". Resolve my comments as you address each.

So long as everything is still green we will be ready to merge once those last couple of changes are made :)

Congrats on the progress, super nice job.

2024-02-16 13:57 UTC, orion-junkins commented on scripts/upload/weather/historical_ecmwf_meteo_to_aws.py
> +# Helper script for uploading historical weather from OpenMeteo to AWS. Intended to be modified & run as needed to upload new historical datasets.
Not really a great automated way to do it, but I want to stress test these scripts pretty aggressively before we rely on them for too much. Fine to merge, no action items, just something to keep in mind that we can talk about next meeting.

2024-02-16 13:57 UTC, orion-junkins commented on src/rlf/forecasting/data_fetching_utilities/weather_provider/open_meteo/ecmwf_adapter.py
> +                    past_days: int = 92,
These two args are unused

2024-02-16 13:57 UTC, orion-junkins commented on src/rlf/forecasting/data_fetching_utilities/weather_provider/open_meteo/ecmwf_adapter.py
> +            "forecast_days": 7
Use them here. Dont hardcode the 92, 7, make them default parameters above and use those variables. Allows us to pass something else in if desired.

2024-02-16 13:57 UTC, orion-junkins commented on src/rlf/forecasting/data_fetching_utilities/weather_provider/open_meteo/parameters.py
> +    "ecmwf_shared": [
Basically go through this list, and for every variable, load the data in the web browser with past_days = 92 (3 months). If the data does not cover the full 92 days, delete it. See this example:
https://open-meteo.com/en/docs/ecmwf-api#hourly=temperature_2m,relative_humidity_2m&past_days=92
Temp_2m has data for the whole window but relative humidity does not, so drop humidity. Just keep the ones that have coverage for the full three months for now. 

We can circle back to this later if we decide we want some of those features.

2024-02-16 13:57 UTC, orion-junkins commented on tests/forecasting/data_fetching_utilities/weather_provider/open_meteo/test_ecmwf_adapter.py
> +    assert response.Hourly().VariablesLength() == len(REAL_COLUMNS)
Nice, I'd say this is plenty for the adapter for now at least. Good work.

2024-02-16 13:57 UTC, orion-junkins commented on tests/forecasting/data_fetching_utilities/weather_provider/test_api_weather_provider_ecmwf.py
> +
Tests look good but get rid of this extra comment.

2024-02-17 13:12 UTC, merged